### PR TITLE
Add queryset cache

### PR DESCRIPTION
**Pull request by bayangan1991**
Add an optional cache to the resolution of extra fields and display conditions.

### CODE REVIEW

**Review by Sticky-Bits — CHANGES_REQUESTED** [review]
Wait, so if we're not using the cache there's no relevant fields? That doesn't seem right?

**Comment by bayangan1991** [comment]
If we aren't using the cache, the relevant fields is set to None so the next if block will always retrieve from the ORM

**Review by jarekwg — APPROVED** [review]
Looks good. How long are we caching for? Have we got confidence we won't get stuck on old data when extra fields change?

**Review by Sticky-Bits — APPROVED** [review]
Sorry, misread the code.

Yep, this looks good.

**Comment by Sticky-Bits** [comment]
> Looks good. How long are we caching for?

I would assume 30 minutes?

`cache.set(cache_key, relevant_fields, 30)`

**Comment by bayangan1991** [comment]
> Looks good. How long are we caching for? Have we got confidence we won't get stuck on old data when extra fields change?

Only 30 seconds, which will be refreshed when called within the context of the importer. No where else is set to use the cache at this current stage.

If we set the caching to be the default then the only issue I can see arising is on a particularly active server, the cache will keep getting refreshed before it can expire. This could be resolved by moving the `cache.set()` to only be called when we fetch from the db so the call will happen every 30 seconds regardless.

**Pull request merged**
